name: Check Code Coverage

on:
    [pull_request]

jobs:
  coverage:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: ["3.10"]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          pip install -U setuptools setuptools_scm wheel
          pip install -e .[testing]
      - name: Run tests with coverage
        env:
          COVERAGE_PROCESS_START: .coveragerc
        run: |
          pytest --cov-report html
          coverage html
      - name: Check coverage
        run: |
          coverage report --fail-under=100
